### ISSUE TITLE
可以提供一下数据库脚本吗

### ISSUE THREAD

**Issue by hongqianzi** [dingsongjie/Pole#1]

**Comment by dingsongjie** [comment]
> _No description provided._
哪部分的数据库脚本，可以描述清楚点么？

**Comment by dingsongjie** [comment]
> _No description provided._

首先，感谢你对这个项目的关注。我当初开发这个项目的原因是 cap 目前只能处理简单的分布式事务,无法处理长流程的分布式事务，类似TCC或者Sagas的方案，对于错误的处理我更喜欢masstransit的方式。但目前我更推荐使用 masstransit 中 request/response proxy + Courier 或者直接用 sagas  的 方式，主要原因是我个人现在没有足够的精力再去把这个框架提升。request/response proxy + Courier 的方式 我做了一个 demo [Masstransit Courier+ request/response](https://github.com/dingsongjie/MasstransitTest),你感兴趣的话可以看看，sagas的方式文档有详细描述我就不多说了.

**Comment by hongqianzi** [comment]
对，我以前基于messagebus做过类似cap的分布式事务，现在要做saga模式的分布式事务，所以没有头绪，看到你的项目。受到了一定的启发，谢谢你的建议

**Comment by dingsongjie** [comment]
> 对，我以前基于messagebus做过类似cap的分布式事务，现在要做saga模式的分布式事务，所以没有头绪，看到你的项目。受到了一定的启发，谢谢你的建议

加油！
